name: Build SpyCast for Windows

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs/ | sh -s -- -y
        echo "$HOME/.cargo/bin" >> $env:GITHUB_PATH
    
    - name: Build project
      run: |
        cargo build --release
    
    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: spycast-windows
        path: target/release/spycast.exe
